xcopy ..\NFTCalvi\src\app\authent\*.* src\app\authent\
xcopy ..\NFTCalvi\src\app\splash\*.* src\app\splash\
xcopy ..\NFTCalvi\src\app\input\*.* src\app\input\
xcopy ..\NFTCalvi\src\app\mywallet\*.* src\app\mywallet\
xcopy ..\NFTCalvi\src\app\signature\*.* src\app\signature\
xcopy ..\NFTCalvi\src\app\faqs\*.* src\app\faqs\
xcopy ..\NFTCalvi\src\app\reversebloc\*.* src\app\reversebloc\
xcopy ..\NFTCalvi\src\app\alias.pipe.ts src\app\
xcopy ..\NFTCalvi\src\app\rescuewallet\*.* src\app\rescuewallet\
xcopy ..\NFTCalvi\src\app\splash\*.* src\app\splash\
xcopy ..\NFTCalvi\src\app\network.service.ts src\app\
xcopy ..\NFTCalvi\src\app\device.service.ts src\app\
xcopy ..\NFTCalvi\src\app\operation.service.ts src\app\
xcopy ..\NFTCalvi\src\nfluent.scss src\
xcopy ..\NFTCalvi\src\app\hourglass\*.*  src\app\hourglass\
xcopy ..\NFTCalvi\src\app\scanner\*.*  src\app\scanner\
xcopy ..\NFTCalvi\src\app\upload-file\*.*  src\app\upload-file\
xcopy ..\NFTCalvi\src\create.ts src\
xcopy ..\NFTCalvi\src\operation.ts src\
xcopy ..\NFTCalvi\src\tools.ts src\
xcopy ..\NFTCalvi\src\nft.ts src\
xcopy ..\NFTCalvi\src\definitions.ts src\
